# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Flask App

on:
  push:
    branches:
      - deploy # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18 # Use your desired Python version

    - name: Install dependencies
      run: |
        ls -lrt
           
    - name: Executing remote copy commands using ssh key
    
      uses: appleboy/scp-action@master
      env:
          username: echiejina
          key: ${{ secrets.DEV_SECRET_01 }}
          host: 34.172.101.81
      with:
          username: echiejina
          key: ${{ secrets.DEV_SECRET_01 }}
          host: 34.172.101.81
          source: "."
          target: /home/echiejina/cbir
    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        username: echiejina
        key: ${{ secrets.DEV_SECRET_01 }}
        host: 34.172.101.81
        script: |
                source ~/venv/bin/activate
                rm -rf ~/cbir-deploy/*
                cp -r ~/cbir/* ~/cbir-deploy
                cd ~/cbir-deploy
                ls -lrt
                pip3 install -r requirements.txt
                pm2 ls
